### ISSUE TITLE
add literals with triple quotes

### ISSUE THREAD

**Issue by ali1k** [Acubed/node-rdf#6]
is there a way to create docstrings ( i.e. literals with triple quotes) when using built-in mode?
I would like to have `string.l()` which returns `""" value """`

**Comment by Acubed** [comment]
The String#l() method doesn't store literals as any particular syntax, it just creates a String with an associated `lang` and/or `type` property.

If you're looking to serialize to a `"""` delimited string, that's hard to do in a general case because the string cannot itself contain the character sequence `"""`. All I can think to do would be to raise an Error in that case.

It can't be terribly hard to do yourself, though:

```javascript
if(string.indexOf('"""')>=0) return string.toNT();
else return '"""' + string + '"""';
```

Make sense?

**Comment by ali1k** [comment]
I'd like to use `"""` to ensure that there are not any strange characters in the string and allow multiline strings. As I see string functions automatically escape special chars which sounds good.  Thanks for your help.

**Comment by Acubed** [comment]
If you think there's any improvements that could be made to the documentation, let me know!

Otherwise if this answers your question, you can close the request.

You're welcome!
